version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: pemiluapp_db
    ports:
      - ${DB_PORT}:3306
    command: mysqld --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASS: ${DB_PASS}
    volumes:
    - pemiluapp-data:/var/lib/mysql

volumes:
  pemiluapp-data:

# SQL_MODE: ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 